### ISSUE TITLE
issues with IPNS

### ISSUE THREAD

**Issue by roscoevanderboom** [Siderus/Orion#221] opened 2019-01-24 03:20 UTC
windows 10

Orion v1.0.10

The first img shows an error message I receive whenever I publish to IPNS. The funny thing is that it still publishes the hash to the namespace.

![failed to publish](https://user-images.githubusercontent.com/39595310/51651927-a7800b80-1f42-11e9-8d77-ad28b9b77790.PNG)

This img shows an error that only happens sometimes. It shows I have no IPNS names, though I have 4. After refreshing all names appeared again. 

![no ipns](https://user-images.githubusercontent.com/39595310/51651942-af3fb000-1f42-11e9-989e-b5ea0bf6aebd.PNG)

Both are tiny bugs and do not actually break the app. They might be more problematic to non-technical users.

**Comment by koalalorenzo** [comment] 2019-01-24 07:50
Thank you for reporting this,
The timeout might be caused by the interaction with the worker. 

Is this happening also when you just open the app?

**Comment by roscoevanderboom** [comment] 2019-01-25 01:38
No. It only happens when I publish to IPNS

**Comment by koalalorenzo** [comment] 2019-01-25 10:10
Bug found and squashed. It will be fixed in next patch release in few days.

**Comment by koalalorenzo** [comment] 2019-01-25 21:53
We have fixed the issue in `v1.0.11-beta`. If you can, please install the beta version and let us know if the issue persists: http://orion.siderus.io/#/beta

**Comment by roscoevanderboom** [comment] 2019-01-26 04:11
sorry to report, no change with `v1.0.11-beta`. Still getting same timeout error. Though the hash is being published successfully. 

IPNS names don't disappear anymore , so that's fixed.

on the upside, IPNS publishing is down to a stable 30secs! Much faster than before and also resolving IPNS address in browser is much faster. This is a great step forward, as IPNS ( in my opinion ) is the best feature of the whole IPFS system.

**Comment by koalalorenzo** [comment] 2019-01-26 09:45
The timeout error will be solved soon as it requires a bunch of heavy changes on the backend.
I will mark it as v1.1+ for now. I am glad that one bug was solved!

**Comment by koalalorenzo** [comment] 2019-01-29 23:32
GitLab MR merged: https://gitlab.com/siderus/orion/ui/merge_requests/87
The next beta version should have a fix for this.

**Closed** 2019-02-03 06:58 UTC
Labels: bug
