### ISSUE TITLE
Does not work when already running a daemon.

### ISSUE THREAD

**Issue by NeoTeo** [Siderus/Orion#89] opened 2018-04-17 10:26 UTC
Orion won't start if you are already running an ipfs daemon. Would be nice if it gave you options to use the existing node, quit the running node or just quit.

**Comment by koalalorenzo** [comment] 2018-04-17 18:10
Working on it. Redmine issue 95.

**Comment by koalalorenzo** [comment] 2018-04-29 17:30
This should be fixed now :) I will close the issue once released (probably next Saturday/Sunday)

**Comment by koalalorenzo** [comment] 2018-05-05 12:05
@NeoTeo could you check and confirm that the pre-release `v0.3` ( https://github.com/Siderus/Orion/releases/tag/v0.3.0 ) solving this issue? 😃

**Comment by NeoTeo** [comment] 2018-05-07 08:30
It doesn't  crash any more. It does however fail to run as it comes up with a timeout alert dialog.
![screen shot 2018-05-07 at 10 29 32](https://user-images.githubusercontent.com/882269/39692628-ac7ab010-51e1-11e8-8ebd-7a4488db96e2.png)

**Comment by koalalorenzo** [comment] 2018-05-07 17:19
We will fix and provide more info about the timeout.

Do you have any chance to run it from the terminal?
1. Clone the repository
2. Follow the instructions here: https://github.com/Siderus/Orion/blob/master/docs/RUN.md

By running in the terminal (`make run`) it will show more logs from the IPFS daemon, and we can understand what is the cause of the timeout.

**Comment by koalalorenzo** [comment] 2018-05-15 11:48
Closing, as it has been fixed :) Please comment/re-open if this issue persist.

**Closed by koalalorenzo** 2018-05-15 11:48 UTC
Labels: bug, in progress, noted
